# Site settings
title: Kody Morey-Gelin
email: info@kody.dog
phone: 8559126900
description: The website of Kody Morey-Gelin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kody.dog" # the base hostname & protocol for your site
#twitter_username: kodydog
instagram_hashtag: "#kodydotdog"
instagram_user_id: 482817452
instagram_access_token: 482817452.33e856b.baac8a33d8394a698c107b21a4b24259

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - bower_components/bootstrap
  - bower_components/jquery
  - bower_components/sassline
  - s3-backup
  - bower.json
  - docker-compose.yml
  - README.md
  - Gruntfile.coffee
  - package.json
