# Site settings
title: Kody Morey-Gelin
email: info@kody.dog
phone: 8559126900
description: The website of Kody Morey-Gelin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kody.dog" # the base hostname & protocol for your site
#twitter_username: kodydog
instagram_hashtag: "#kodydotdog"
instagram_access_token: 5dd7f025dec54bf497e878a233964e55

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - bower_components/bootstrap
  - bower_components/jquery
  - bower_components/sassline
  - bower.json
  - docker-compose.yml
  - README.md
  - Gruntfile.coffee
  - package.json
