# Site settings
title: Kody the Dog
email: info@kody.dog
description: >
  The website of Kody the dog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kody.dog" # the base hostname & protocol for your site
#twitter_username: kodydog

# Build settings
markdown: kramdown
