jekyll:
  image: jekyll/jekyll:2.5.3
  volumes:
    - ./:/srv/jekyll
  ports:
    - 4000:4000

bower:
  image: digitallyseamless/nodejs-bower-grunt
  working_dir: '/srv/jekyll'
  entrypoint: bower
  volumes:
    - ./:/srv/jekyll

npm:
  image: digitallyseamless/nodejs-bower-grunt
  working_dir: '/srv/jekyll'
  entrypoint: npm
  volumes:
    - ./:/srv/jekyll

grunt:
  image: digitallyseamless/nodejs-bower-grunt
  working_dir: '/srv/jekyll'
  entrypoint: grunt
  volumes:
    - ./:/srv/jekyll
